docs(samples): add initial sample codes
googleapis/python-dialogflow-cx pull request #13
Opened 2020-09-29 18:53 UTC by wuyuexin

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-dialogflow-cx/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #12  🦕

2020-09-29 19:59 UTC, kurtisvg requested changes

2020-09-29 19:59 UTC, kurtisvg commented on samples/snippets/detect_intent_stream.py
> +def detect_intent_stream(agent, session_id, audio_file_path, language_code):
Please add some hints to the user to what these values mean. You can do one of either of the following:

(preferred) Add a simple overloaded method that demonstrates initalization and calles the underlying function:
```python 
# [START dialogflow_detect_intent_stream]
def run_sample():
    # TODO(developer): Replace these values when running the function
    agent = "YOUR-AGENT-ID"  # https://link.to.more.info.on.agents
    # ...
    detect_intent_stream(agent, session_id, audio_file_path, language_code):

def detect_intent_stream(agent, session_id, audio_file_path, language_code):
```

2020-09-29 19:59 UTC, kurtisvg commented on samples/snippets/detect_intent_stream.py
> +    session_path = "{}/sessions/{}".format(agent, session_id)
Please use f-strings in modern python versions:
```suggestion
    session_path = f"{agent}/sessions/{session_id}"
```

2020-09-29 19:59 UTC, kurtisvg commented on samples/snippets/detect_intent_stream.py
> +    responses = session_client.streaming_detect_intent(requests=requests)
nit: inline this argument
```suggestion
    responses = session_client.streaming_detect_intent(requests=request_generator())
```

2020-09-29 19:59 UTC, kurtisvg commented on samples/snippets/detect_intent_stream.py
> +    session_path = "{}/sessions/{}".format(agent, session_id)
(same for other places)

2020-09-29 19:59 UTC, kurtisvg commented on samples/snippets/detect_intent_stream.py
> +    )
nit: This is way more readable if you break into different lines
```suggestion
    response_messages = [" ".join(msg.text.text) for msg in response.query_result.response_messages]
    print(f"Response text: {" ".join(response_messages}\n")
```

2020-09-29 19:59 UTC, kurtisvg commented on samples/snippets/detect_intent_stream_test.py
> +AUDIO = "{}/resources/hello.wav".format(DIRNAME)
The location for external resources for the test should be passed in by env vars - See [External Resources](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#external-resources)

2020-09-29 23:45 UTC, kurtisvg requested changes

2020-09-29 23:45 UTC, kurtisvg commented on samples/snippets/detect_intent_audio.py
> +    )
nit:
```suggestion
    # For more info on agents see https://cloud.google.com/dialogflow/cx/docs/concept/agent
    agent_id = "YOUR-AGENT-ID" 
```

2020-09-29 23:45 UTC, kurtisvg commented on samples/snippets/detect_intent_audio.py
> +    )  # https://cloud.google.com/dialogflow/cx/docs/concept/session
```suggestion
    # For more information on sessions see https://cloud.google.com/dialogflow/cx/docs/concept/session
    session_id = str(uuid.uuid4())  
```

2020-09-29 23:45 UTC, kurtisvg commented on samples/snippets/detect_intent_audio.py
> +    language_code = "en-us"
Is this always `en-us`? If it is, can we move below into the sample? If not, can add a link to a list of supported options?

2020-09-29 23:45 UTC, kurtisvg commented on samples/snippets/detect_intent_audio.py
> +# [START dialogflow_detect_intent_audio]
This region tag should be above the `run_sample` function

2020-09-29 23:46 UTC, kurtisvg commented
@busunkim96 I don't see any Kokoro tests running on this repo. Is that intentional?

2020-09-29 23:50 UTC, busunkim96 commented
@kurtisvg Kokoro isn't running is because author is outside the org. I also need to add samples configs though. Opened 334490453.

2020-09-29 23:53 UTC, kurtisvg commented
> @kurtisvg Kokoro isn't running is because author is outside the org. I also need to add samples configs though. Opened 334490453.

That was specifically what I was referring too :)

2020-09-30 19:54 UTC, kurtisvg approved these changes

2020-09-30 19:54 UTC, kurtisvg commented
@wuyuexin Let me know if you need help merging this.

2020-09-30 20:00 UTC, wuyuexin commented
> @wuyuexin Let me know if you need help merging this.

Yes, I'm not familiar with the merging process. Is there anything I need to do?

2020-09-30 20:02 UTC, busunkim96 commented
👋  There's a small tweak I want to make to the `noxfile`/`noxfile_config`. I'll merge it for you right after that @wuyuexin.

Side note, I think I'll have to add another PR template for samples that looks like the one in python-docs-samples.

2020-09-30 20:11 UTC, busunkim96 approved these changes

2020-09-30 20:34 UTC, merged