docs: add streaming detect intent with partial response sample
googleapis/python-dialogflow-cx pull request #414
Opened 2022-06-30 21:36 UTC by nicain

This snippet mirrors the functionality from the NodeJS snippet.

2022-06-30 21:50 UTC, kweinmeister requested changes

2022-06-30 21:50 UTC, kweinmeister commented on samples/snippets/streaming_detect_intent_partial_response.py
> +    # agent_components = AgentsClient.parse_agent_path(f'projects/{project_id}/locations/{location}/agents/{agent_id}')
Are these commented-out lines intentional? If so, consider adding a comment.

2022-06-30 21:50 UTC, kweinmeister commented on samples/snippets/streaming_detect_intent_partial_response.py
> +  audio_file_name = '/usr/local/google/home/nicholascain/nodejs-dialogflow-cx/samples/resources/book_a_room.wav'
Both this and the line above are pointing to local resources

2022-06-30 21:50 UTC, kweinmeister commented on samples/snippets/streaming_detect_intent_partial_response.py
> +from google.cloud.dialogflowcx_v3beta1.services import sessions
Let's use v3 rather than v3beta1 throughout if possible

2022-06-30 23:53 UTC, nicain commented on samples/snippets/streaming_detect_intent_partial_response.py
> +    # agent_components = AgentsClient.parse_agent_path(f'projects/{project_id}/locations/{location}/agents/{agent_id}')
No, they are removed.

2022-06-30 23:54 UTC, nicain commented on samples/snippets/streaming_detect_intent_partial_response.py
> +from google.cloud.dialogflowcx_v3beta1.services import sessions
Done

2022-07-01 00:07 UTC, kweinmeister approved these changes

2022-07-01 00:23 UTC, merged